#!/usr/bin/env bash
set -euo pipefail

tmpbase="$(mktemp -d)"
src="$tmpbase/template"
out="$tmpbase/My-Graph_Project.demo"
template_version="$(sed -n 's/^version = "\([^"]*\)"/\1/p' pyproject.toml | head -n 1)"

cleanup() {
  rm -rf "$tmpbase"
}
trap cleanup EXIT

rsync -a \
  --exclude '.git' \
  --exclude '.venv' \
  --exclude '.pytest_cache' \
  --exclude '.ruff_cache' \
  --exclude '.idea' \
  --exclude '__pycache__' \
  ./ "$src"/

(
  cd "$src"
  git init -q
  git config user.email "template-smoke@example.com"
  git config user.name "Template Smoke"
  git add .
  git -c commit.gpgsign=false commit -qm "template snapshot"
)

(
  cd "$src"
  copier copy . "$out" --trust --defaults \
    --data api_key='abc123' \
    --data validate_api_key=false \
    --data source_type='sitemap' \
    --data sitemap_url='https://example.com/sitemap.xml' \
    --data sitemap_url_pattern='' \
    --data profiles='["default","eu"]' \
    --data default_profile='default'
)

test -f "$out/worai.toml"
test -f "$out/pyproject.toml"
test -f "$out/README.md"
test ! -f "$out/README.md.jinja"
test -f "$out/AGENTS.md"
test ! -f "$out/AGENTS.md.jinja"
test -f "$out/.github/workflows/graph-sync.yml"
test -f "$out/.env"
test -d "$out/src/graph_sync_my_graph_project_demo"
test ! -d "$out/src/acme_kg"
test ! -f "$out/.github/workflows/template-smoke.yml"
test -d "$out/.git"
test ! -f "$out/copier.yml"
test ! -d "$out/.copier-tasks"
test ! -f "$out/.copier-answers.yml"
test ! -f "$out/TODO.md"
test ! -d "$out/specs"
test ! -d "$out/tests"

search() {
  local pattern="$1"
  local file="$2"
  if command -v rg >/dev/null 2>&1; then
    rg -n "$pattern" "$file" >/dev/null
  else
    grep -nE "$pattern" "$file" >/dev/null
  fi
}

if search '\{\{|\{%' "$out/worai.toml"; then
  echo "Unrendered template syntax found in generated worai.toml"
  exit 1
fi

search 'sitemap_url = "https://example.com/sitemap.xml"' "$out/worai.toml"
search 'overwrite = true' "$out/worai.toml"
search 'log_level = "warning"' "$out/worai.toml"
search 'graph_write_strategy = "put"' "$out/worai.toml"
search 'materialization_backend = "worph"' "$out/worai.toml"
search 'canonical_id_strategy = "dependency_graph"' "$out/worai.toml"
search 'concurrency = 4' "$out/worai.toml"
search 'postprocessor_pool_size = 2' "$out/worai.toml"
search 'postprocessor_runtime = "persistent"' "$out/worai.toml"
search 'shacl_pool_size = 1' "$out/worai.toml"
search 'shacl_exclude_builtin_shapes = \["google-course", "google-recipe"\]' "$out/worai.toml"
search 'mapping_pool_size = 1' "$out/worai.toml"
search 'ingest_loader = "crawler"' "$out/worai.toml"
search 'crawler_js_render_mode = "disabled"' "$out/worai.toml"
search 'crawler_proxy_mode = "disabled"' "$out/worai.toml"
search '# ingest_timeout_ms = 600000' "$out/worai.toml"
search 'ingest_retry_attempts = 2' "$out/worai.toml"
search 'ingest_retry_backoff_ms = 3000' "$out/worai.toml"
search 'google_search_console = false' "$out/worai.toml"
search 'api_key = "\$\{WORDLIFT_API_KEY\}"' "$out/worai.toml"
search 'wordlift/graph-sync@v6' "$out/.github/workflows/graph-sync.yml"
search 'graph_kpis_enabled: true' "$out/.github/workflows/graph-sync.yml"
if search 'worai_version:' "$out/.github/workflows/graph-sync.yml"; then
  echo "Generated workflow must let the graph-sync action select the worai version"
  exit 1
fi
search '^name = "graph-sync-my-graph-project-demo"$' "$out/pyproject.toml"
search '^version = "0.1.0"$' "$out/pyproject.toml"
search '^description = "Graph Sync project for my-graph-project-demo"$' "$out/pyproject.toml"
search '^# Graph Sync Project$' "$out/README.md"
search 'Project package: `graph-sync-my-graph-project-demo`' "$out/README.md"
search 'Runtime module: `graph_sync_my_graph_project_demo`' "$out/README.md"
search 'graph-sync-agent-kit:graph-sync-curator' "$out/README.md"
search '\$graph-sync-curator' "$out/README.md"
search 'docs/QUICKSTART.md' "$out/README.md"
search 'initial commit' "$out/README.md"
search 'Codex prompt:' "$out/docs/QUICKSTART.md"
search 'graph-sync-agent-kit:graph-sync-curator' "$out/docs/QUICKSTART.md"
search 'Claude Code prompt:' "$out/docs/QUICKSTART.md"
search '\$graph-sync-curator' "$out/docs/QUICKSTART.md"
search 'wordlift/graph-sync-agent-kit' "$out/AGENTS.md"
search 'wordlift/agent-marketplace' "$out/AGENTS.md"
search 'class = "graph_sync_my_graph_project_demo\.postprocessors\.youtube:YouTubePostprocessor"' "$out/profiles/_base/postprocessors.example.toml"

if ! grep -Fx "# Generated by graph-sync-template v${template_version}" "$out/pyproject.toml" >/dev/null; then
  echo "Generated pyproject.toml is missing template version metadata"
  exit 1
fi

if search 'git@github.com:wordlift/graph-sync-agent-kit.git' "$out/AGENTS.md"; then
  echo "Generated AGENTS.md still references direct skill installation from git"
  exit 1
fi

(
  cd "$out"
  test "$(git rev-list --count HEAD)" -eq 1
  test "$(git log --format=%s -1)" = "initial commit"
  if [ "$(git log --format=%an -1)" != "Graph Sync Project" ]; then
    echo "Generated git commit has unexpected author name"
    exit 1
  fi
  if [ "$(git log --format=%ae -1)" != "dev@wordlift.io" ]; then
    echo "Generated git commit has unexpected author email"
    exit 1
  fi
  git diff --quiet
  git diff --cached --quiet
  git check-ignore -q .env
  git check-ignore -q .private/smoke-secret
  if git ls-files --error-unmatch .env >/dev/null 2>&1; then
    echo "Generated .env was tracked in initial commit"
    exit 1
  fi
)

if search 'Graph Sync Template|Template Contract|template-smoke|Generate from GitHub' "$out/README.md"; then
  echo "Generated README still contains template-maintainer content"
  exit 1
fi

if search '\\n' "$out/.env"; then
  echo "Generated .env contains literal \\\\n sequences"
  exit 1
fi

env_lines="$(wc -l < "$out/.env" | tr -d '[:space:]')"
if [ "$env_lines" -ne 3 ]; then
  echo "Generated .env has unexpected line count: $env_lines"
  exit 1
fi

echo "Template smoke render passed."
